version: '3.2'
services:
  flask_app:
    build:
      context: flask_app
    stop_signal: SIGKILL
    ports:
      - 8080:8080
    networks:
      - webnet

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - webnet


networks:
  webnet:
